## Add a TODO comment indicating the reason for each rejected dependency upgrade added to this list, and what should be done to resolve it (i.e. handle it through a story, etc).
reject: [
  # TODO: Upgrading ws is causing some incompatibility issues connecting to sdk-scheme-adapter ws server and causing some test failures
  "ws",
  # TODO: Upgrading axios is breaking lot of unit tests. It might be because of breaking changes in axios. 
  "axios",
  # TODO: Upgrading jest is causing test failures
  "jest"

]
